// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCp8vlcy8eus0X-lNEaJ4mnYfX0sA03zpU',
    appId: '1:995023670046:web:971f47c02e84501f4bd70f',
    messagingSenderId: '995023670046',
    projectId: 'auth-1c2b3',
    authDomain: 'auth-1c2b3.firebaseapp.com',
    storageBucket: 'auth-1c2b3.appspot.com',
    measurementId: 'G-81GGML62YP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDHfvt8sIVgK7RPVuKwfZ0rkc7TxGyZgQ',
    appId: '1:995023670046:android:5b9a74228b4191764bd70f',
    messagingSenderId: '995023670046',
    projectId: 'auth-1c2b3',
    storageBucket: 'auth-1c2b3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaBLpHyUVnGCJsj-d0UjzplwtpRfk1ca4',
    appId: '1:995023670046:ios:5ea0752a07f6eef94bd70f',
    messagingSenderId: '995023670046',
    projectId: 'auth-1c2b3',
    storageBucket: 'auth-1c2b3.appspot.com',
    iosBundleId: 'com.example.praktikum2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaBLpHyUVnGCJsj-d0UjzplwtpRfk1ca4',
    appId: '1:995023670046:ios:8cc19f474ab64a8e4bd70f',
    messagingSenderId: '995023670046',
    projectId: 'auth-1c2b3',
    storageBucket: 'auth-1c2b3.appspot.com',
    iosBundleId: 'com.example.praktikum2.RunnerTests',
  );
}
